config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :students
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
resources :users
resources :articles
  # Defines the root path route ("/")
  # root "articles#index"
  root "welcome#home"
  get 'signup' , to: 'users#new'
  post 'users'  , to: 'users#create'

  get 'login' , to: 'sessions#new'
  post 'login' , to: 'sessions#create'

  get 'logout' , to: 'sessions#destroy'

  resources :categories
  # get 'articles/all/:id' , to: 'articles#all'
  # get 'articles/viewall'  , to: 'articles#viewall'
  # post 'articles' , to: 'articles#index'
  # get 'userdash' , to: 'article#new'
  # post 'articles' , to: 'articles#create'
end

app/models/user.rb
class User < ActiveRecord::Base
has_many :articles
# has_secure_password

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_user, only: [:show]
before_action :required , except: [:index , :new , :create]
def new
@user = User.new
end
def create
    @user = User.new(users_params)
    if @user.save
        # flash.alert = "User Successfully Created"
        # flash.alert = " Welcome Mr. #{@user.username}"
        session[:user_id] = @user.id
        redirect_to user_path(@user)
    else
    render 'new'
    end

end
def show

# @users_articles = @user.articles.paginate(page: params(:page) , per_page: 1)
@users = @user.articles
end
def index
    @users = User.all 
end

    def users_params
        params.require(:user).permit(:username , :email , :password_digest)
    end

    def set_user
        @user = User.find(params[:id])
    end
end

app/views/users/index.html.erb
<h1> List of Our Precious Users </h1>
<%= link_to "Homepage" , root_path %>

<table>
<tr>
<th>Id</th>
<th>Name</th>
<th>Email</th>
<th>Total Number of Articles</th>
</tr>
<% @users.each do |u|%>
<tr>
<td><%= u.id%></td>
<td><%= u.username%></td> 
<td><%= u.email %></td> 
<td><%= link_to u.articles.count , article_path(u) %> </td>


</tr>
<% end %>
</table>

app/views/users/new.html.erb
<h1> Please Signup here </h1>

<%= form_for @user do |u| %>
<p>
<%= u.label :Enter_Username%>
<%= u.text_field :username%>
</p>
<p>
<%= u.label :Enter_Email%>
<%= u.email_field :email%>
</p>
<p>
<%= u.label :Enter_Password%>
<%= u.password_field :password_digest %>
</p>
<p>
<%= u.submit "Signup"%>
</p><br/>
<%= link_to 'Homepage' , root_path%>
<%end%>

app/views/users/show.html.erb
<%= gravatar_for @user, size: 150 %>
<br>
<h1> Welcome Mr <%= @user.username %> 
<br>
Id: <%= session[:user_id] %> <br>
Username <%= session[:username] %><br>
<%= link_to "Create New Articles" , new_article_path %> | <%= link_to 'Update your Profile' %>  <% if current_user.admin? %>  | <%= link_to "Create Category" , new_category_path%> <%end%>


<h3>Articles by this User</h3>

<table>
<tr>
<th>Topic</th>
<th>Description</th>
<th>Show</th>
<th>Edit</th>
<th>Delete</th>
</tr>

<% @user.articles.each do |a|%>
<tr>
<th><%= a.name %></th>
<th><%= a.description %></th>
<th><%= link_to "show" , article_path(a.id) %></th>
<th><%= link_to "Edit" , edit_article_path(a) %></th>
<td><%= link_to "Delete" ,article_path(a), method: :delete, data: { 
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></td> 

</tr>
<%end%>

</table>

<% if current_user.admin?%>
<h1>Total number of Users: </h1> <%= User.count %>
<br><h4>Users Name List</h4>
<ul>

<% User.all.each do |u| %>
<li><%= u.username%></li>
<%end%>
</ul>
<%end%>